# ============================================================
# RISK ENGINE DYNAMIC V1
# ============================================================
# Dynamic route risk analysis for the GIS + AI Pipeline
# Routing Decision Support System
#
# INPUT:
#   - Routes generated by routing_engine_v2.py
#   - DEM
#   - LULC_FINAL.tif
#
# OUTPUT FOR EACH ROUTE:
#   - Mean slope
#   - Maximum slope
#   - Terrain risk
#   - LULC risk
#   - Combined risk
#   - High-risk cells
#   - High-risk distance
#   - High-risk sections
#   - LULC exposure
#   - Slope exposure
#
# ============================================================

import os
import sys
import json
import math

import numpy as np
import pandas as pd
import rasterio


# ============================================================
# PROJECT PATHS
# ============================================================

BASE_DIR = r"I:/Kashyap/Route"

CODES_DIR = os.path.join(
    BASE_DIR,
    "codes"
)

LULC_PATH = os.path.join(
    BASE_DIR,
    "LULC",
    "LULC_FINAL.tif"
)

DEM_PATH = os.path.join(
    BASE_DIR,
    "DEM",
    "DEM_ASSAM.tif"
)

if not os.path.exists(DEM_PATH):

    DEM_PATH = os.path.join(
        BASE_DIR,
        "DEM_ASSAM.tif"
    )

OUTPUT_DIR = os.path.join(
    BASE_DIR,
    "OUTPUT",
    "dashboard"
)


# ============================================================
# RISK CONFIGURATION
# ============================================================

# Terrain / LULC weighting

TERRAIN_WEIGHT = 0.50

LULC_WEIGHT = 0.50


# ------------------------------------------------------------
# Slope risk thresholds
# ------------------------------------------------------------

SLOPE_LOW_MAX = 5.0

SLOPE_MODERATE_MAX = 15.0

SLOPE_HIGH_MAX = 30.0


# ------------------------------------------------------------
# LULC risk mapping
#
# User-defined semantic classes
# ------------------------------------------------------------

LULC_RISK = {

    0: 0.50,   # Unknown / unidentified

    1: 0.60,   # Agriculture

    2: 0.30,   # Vegetation

    3: 0.40,   # Grassland

    4: 1.00,   # Rivers / water bodies

    5: 0.90    # Built-up
}


# ============================================================
# RISK ENGINE
# ============================================================

class DynamicRiskEngine:

    def __init__(
        self,
        dem_path=DEM_PATH,
        lulc_path=LULC_PATH
    ):

        print("=" * 70)
        print("INITIALIZING DYNAMIC RISK ENGINE V1")
        print("=" * 70)

        self.dem_path = dem_path

        self.lulc_path = lulc_path

        # ----------------------------------------------------
        # Check files
        # ----------------------------------------------------

        if not os.path.exists(
            self.dem_path
        ):

            raise FileNotFoundError(
                f"\nDEM not found:\n{self.dem_path}"
            )

        if not os.path.exists(
            self.lulc_path
        ):

            raise FileNotFoundError(
                f"\nLULC raster not found:\n{self.lulc_path}"
            )

        # ----------------------------------------------------
        # Load DEM
        # ----------------------------------------------------

        print(
            "\nLoading DEM..."
        )

        with rasterio.open(
            self.dem_path
        ) as src:

            self.dem = src.read(
                1
            ).astype(
                np.float64
            )

            self.transform = src.transform

            self.crs = src.crs

            self.bounds = src.bounds

            self.height = src.height

            self.width = src.width

            self.dem_nodata = src.nodata

        print(
            "DEM shape:",
            self.dem.shape
        )

        print(
            "DEM CRS:",
            self.crs
        )

        # ----------------------------------------------------
        # Load LULC
        # ----------------------------------------------------

        print(
            "\nLoading LULC..."
        )

        with rasterio.open(
            self.lulc_path
        ) as src:

            self.lulc = src.read(
                1
            )

            self.lulc_transform = src.transform

            self.lulc_crs = src.crs

            self.lulc_nodata = src.nodata

            self.lulc_height = src.height

            self.lulc_width = src.width

        print(
            "LULC shape:",
            self.lulc.shape
        )

        print(
            "LULC CRS:",
            self.lulc_crs
        )

        # ----------------------------------------------------
        # Validate alignment
        # ----------------------------------------------------

        if self.dem.shape != self.lulc.shape:

            raise ValueError(
                "\nDEM and LULC dimensions do not match.\n"
                f"DEM: {self.dem.shape}\n"
                f"LULC: {self.lulc.shape}"
            )

        # ----------------------------------------------------
        # Validate transforms
        # ----------------------------------------------------

        if not np.allclose(
            np.array(
                self.transform
            ),
            np.array(
                self.lulc_transform
            )
        ):

            raise ValueError(
                "\nDEM and LULC transforms do not match.\n"
                "The rasters are not aligned."
            )

        # ----------------------------------------------------
        # Calculate slope
        # ----------------------------------------------------

        print(
            "\nCalculating slope..."
        )

        self.slope = self._calculate_slope()

        print(
            "Slope calculated."
        )

        print(
            "Mean slope:",
            round(
                float(
                    np.nanmean(
                        self.slope
                    )
                ),
                3
            ),
            "degrees"
        )

        print("=" * 70)


    # ========================================================
    # CALCULATE SLOPE
    # ========================================================

    def _calculate_slope(
        self
    ):

        # ----------------------------------------------------
        # Raster resolution
        #
        # Project raster is geographic EPSG:4326.
        # Convert degrees approximately to metres.
        # ----------------------------------------------------

        pixel_width_deg = abs(
            self.transform.a
        )

        pixel_height_deg = abs(
            self.transform.e
        )

        # Project centre latitude

        center_lat = (
            self.bounds.top
            +
            self.bounds.bottom
        ) / 2.0

        lat_rad = math.radians(
            center_lat
        )

        # Approximate metres / degree

        metres_per_degree_lat = 111320.0

        metres_per_degree_lon = (
            111320.0
            *
            math.cos(lat_rad)
        )

        pixel_width_m = (
            pixel_width_deg
            *
            metres_per_degree_lon
        )

        pixel_height_m = (
            pixel_height_deg
            *
            metres_per_degree_lat
        )

        # ----------------------------------------------------
        # Replace invalid DEM values
        # ----------------------------------------------------

        dem = self.dem.copy()

        if self.dem_nodata is not None:

            dem[
                dem == self.dem_nodata
            ] = np.nan

        dem[
            ~np.isfinite(dem)
        ] = np.nan

        # ----------------------------------------------------
        # Gradient
        # ----------------------------------------------------

        gradient_y, gradient_x = np.gradient(
            dem,
            pixel_height_m,
            pixel_width_m
        )

        slope_radians = np.arctan(
            np.sqrt(
                gradient_x ** 2
                +
                gradient_y ** 2
            )
        )

        slope_degrees = np.degrees(
            slope_radians
        )

        return slope_degrees


    # ========================================================
    # SLOPE -> RISK
    # ========================================================

    def slope_to_risk(
        self,
        slope
    ):

        risk = np.zeros_like(
            slope,
            dtype=np.float64
        )

        valid = np.isfinite(
            slope
        )

        # ----------------------------------------------------
        # 0–5 degrees
        # ----------------------------------------------------

        mask = (
            valid
            &
            (slope <= SLOPE_LOW_MAX)
        )

        risk[mask] = 0.10

        # ----------------------------------------------------
        # >5–15 degrees
        # ----------------------------------------------------

        mask = (
            valid
            &
            (slope > SLOPE_LOW_MAX)
            &
            (slope <= SLOPE_MODERATE_MAX)
        )

        risk[mask] = 0.35

        # ----------------------------------------------------
        # >15–30 degrees
        # ----------------------------------------------------

        mask = (
            valid
            &
            (slope > SLOPE_MODERATE_MAX)
            &
            (slope <= SLOPE_HIGH_MAX)
        )

        risk[mask] = 0.70

        # ----------------------------------------------------
        # >30 degrees
        # ----------------------------------------------------

        mask = (
            valid
            &
            (slope > SLOPE_HIGH_MAX)
        )

        risk[mask] = 1.00

        # ----------------------------------------------------
        # Invalid cells
        # ----------------------------------------------------

        risk[
            ~valid
        ] = np.nan

        return risk


    # ========================================================
    # LULC -> RISK
    # ========================================================

    def create_lulc_risk_surface(
        self
    ):

        risk = np.full(
            self.lulc.shape,
            np.nan,
            dtype=np.float64
        )

        # ----------------------------------------------------
        # Handle NoData
        # ----------------------------------------------------

        valid = np.ones(
            self.lulc.shape,
            dtype=bool
        )

        if self.lulc_nodata is not None:

            valid &= (
                self.lulc
                !=
                self.lulc_nodata
            )

        # ----------------------------------------------------
        # Map classes
        # ----------------------------------------------------

        for class_value, class_risk in LULC_RISK.items():

            mask = (
                valid
                &
                (self.lulc == class_value)
            )

            risk[
                mask
            ] = class_risk

        # ----------------------------------------------------
        # Unknown classes
        # ----------------------------------------------------

        unknown = (
            valid
            &
            ~np.isfinite(risk)
        )

        risk[
            unknown
        ] = 0.50

        return risk


    # ========================================================
    # CREATE RISK SURFACES
    # ========================================================

    def create_risk_surfaces(
        self
    ):

        self.terrain_risk = (
            self.slope_to_risk(
                self.slope
            )
        )

        self.lulc_risk = (
            self.create_lulc_risk_surface()
        )

        self.combined_risk = (
            TERRAIN_WEIGHT
            *
            self.terrain_risk
            +
            LULC_WEIGHT
            *
            self.lulc_risk
        )

        return (
            self.terrain_risk,
            self.lulc_risk,
            self.combined_risk
        )


    # ========================================================
    # ROUTE CELL VALUES
    # ========================================================

    def extract_route_values(
        self,
        route
    ):

        rows = []

        cols = []

        for row, col in route:

            if (
                0 <= row < self.height
                and
                0 <= col < self.width
            ):

                rows.append(
                    int(row)
                )

                cols.append(
                    int(col)
                )

        rows = np.array(
            rows,
            dtype=np.int32
        )

        cols = np.array(
            cols,
            dtype=np.int32
        )

        return rows, cols


    # ========================================================
    # ROUTE RISK ANALYSIS
    # ========================================================

    def analyze_route(
        self,
        route,
        route_name
    ):

        if route is None:

            return {

                "route_name":
                route_name,

                "status":
                "failed"
            }

        rows, cols = (
            self.extract_route_values(
                route
            )
        )

        if len(rows) == 0:

            return {

                "route_name":
                route_name,

                "status":
                "failed"
            }

        slope_values = self.slope[
            rows,
            cols
        ]

        terrain_values = self.terrain_risk[
            rows,
            cols
        ]

        lulc_values = self.lulc_risk[
            rows,
            cols
        ]

        combined_values = self.combined_risk[
            rows,
            cols
        ]

        lulc_values_raw = self.lulc[
            rows,
            cols
        ]

        # ----------------------------------------------------
        # Valid values
        # ----------------------------------------------------

        valid_slope = slope_values[
            np.isfinite(
                slope_values
            )
        ]

        valid_terrain = terrain_values[
            np.isfinite(
                terrain_values
            )
        ]

        valid_lulc = lulc_values[
            np.isfinite(
                lulc_values
            )
        ]

        valid_combined = combined_values[
            np.isfinite(
                combined_values
            )
        ]

        # ----------------------------------------------------
        # Statistics
        # ----------------------------------------------------

        mean_slope = (
            float(
                np.mean(
                    valid_slope
                )
            )
            if len(valid_slope) > 0
            else 0.0
        )

        max_slope = (
            float(
                np.max(
                    valid_slope
                )
            )
            if len(valid_slope) > 0
            else 0.0
        )

        mean_terrain_risk = (
            float(
                np.mean(
                    valid_terrain
                )
            )
            if len(valid_terrain) > 0
            else 0.0
        )

        mean_lulc_risk = (
            float(
                np.mean(
                    valid_lulc
                )
            )
            if len(valid_lulc) > 0
            else 0.0
        )

        combined_risk = (
            float(
                np.mean(
                    valid_combined
                )
            )
            if len(valid_combined) > 0
            else 0.0
        )

        # ----------------------------------------------------
        # Slope exposure
        # ----------------------------------------------------

        slope_low = np.sum(
            valid_slope <= 5.0
        )

        slope_moderate = np.sum(
            (
                valid_slope > 5.0
            )
            &
            (
                valid_slope <= 15.0
            )
        )

        slope_high = np.sum(
            (
                valid_slope > 15.0
            )
            &
            (
                valid_slope <= 30.0
            )
        )

        slope_very_high = np.sum(
            valid_slope > 30.0
        )

        # ----------------------------------------------------
        # High-risk cells
        # ----------------------------------------------------

        high_risk_mask = (
            valid_combined
            >=
            0.70
        )

        high_risk_cells = int(
            np.sum(
                high_risk_mask
            )
        )

        # ----------------------------------------------------
        # Route physical distance
        #
        # Approximate local pixel dimensions
        # ----------------------------------------------------

        pixel_width_deg = abs(
            self.transform.a
        )

        pixel_height_deg = abs(
            self.transform.e
        )

        center_lat = (
            self.bounds.top
            +
            self.bounds.bottom
        ) / 2.0

        lat_rad = math.radians(
            center_lat
        )

        metres_per_degree_lat = 111320.0

        metres_per_degree_lon = (
            111320.0
            *
            math.cos(lat_rad)
        )

        pixel_width_m = (
            pixel_width_deg
            *
            metres_per_degree_lon
        )

        pixel_height_m = (
            pixel_height_deg
            *
            metres_per_degree_lat
        )

        route_distance_m = 0.0

        for i in range(
            len(route) - 1
        ):

            r1, c1 = route[i]

            r2, c2 = route[i + 1]

            dr = (
                r2 - r1
            )

            dc = (
                c2 - c1
            )

            segment_distance = math.sqrt(

                (
                    dr
                    *
                    pixel_height_m
                )
                ** 2
                +
                (
                    dc
                    *
                    pixel_width_m
                )
                ** 2
            )

            route_distance_m += (
                segment_distance
            )

        # ----------------------------------------------------
        # High-risk distance
        # ----------------------------------------------------

        high_risk_distance_m = 0.0

        high_risk_sections = 0

        in_high_risk_section = False

        section_start = None

        section_records = []

        for i in range(
            len(route)
        ):

            value = combined_values[
                i
            ]

            is_high = (
                np.isfinite(value)
                and
                value >= 0.70
            )

            if is_high:

                if not in_high_risk_section:

                    in_high_risk_section = True

                    section_start = i

                if i < len(route) - 1:

                    r1, c1 = route[i]

                    r2, c2 = route[i + 1]

                    dr = r2 - r1

                    dc = c2 - c1

                    segment_distance = math.sqrt(

                        (
                            dr
                            *
                            pixel_height_m
                        )
                        ** 2
                        +
                        (
                            dc
                            *
                            pixel_width_m
                        )
                        ** 2
                    )

                    high_risk_distance_m += (
                        segment_distance
                    )

            else:

                if in_high_risk_section:

                    section_end = i - 1

                    high_risk_sections += 1

                    start_cell = route[
                        section_start
                    ]

                    end_cell = route[
                        section_end
                    ]

                    section_records.append(
                        {

                            "route_name":
                            route_name,

                            "section_id":
                            high_risk_sections,

                            "start_row":
                            int(
                                start_cell[0]
                            ),

                            "start_col":
                            int(
                                start_cell[1]
                            ),

                            "end_row":
                            int(
                                end_cell[0]
                            ),

                            "end_col":
                            int(
                                end_cell[1]
                            ),

                            "cells":
                            int(
                                section_end
                                -
                                section_start
                                +
                                1
                            )
                        }
                    )

                    in_high_risk_section = False

                    section_start = None

        # ----------------------------------------------------
        # Close final section
        # ----------------------------------------------------

        if in_high_risk_section:

            section_end = (
                len(route) - 1
            )

            high_risk_sections += 1

            start_cell = route[
                section_start
            ]

            end_cell = route[
                section_end
            ]

            section_records.append(
                {

                    "route_name":
                    route_name,

                    "section_id":
                    high_risk_sections,

                    "start_row":
                    int(
                        start_cell[0]
                    ),

                    "start_col":
                    int(
                        start_cell[1]
                    ),

                    "end_row":
                    int(
                        end_cell[0]
                    ),

                    "end_col":
                    int(
                        end_cell[1]
                    ),

                    "cells":
                    int(
                        section_end
                        -
                        section_start
                        +
                        1
                    )
                }
            )

        # ----------------------------------------------------
        # Risk percentage
        # ----------------------------------------------------

        high_risk_percentage = (

            high_risk_cells
            /
            len(route)
            *
            100.0

        )

        # ----------------------------------------------------
        # Risk category
        # ----------------------------------------------------

        if combined_risk < 0.25:

            risk_category = "Low"

        elif combined_risk < 0.50:

            risk_category = "Moderate"

        elif combined_risk < 0.70:

            risk_category = "High"

        else:

            risk_category = "Very High"

        # ----------------------------------------------------
        # LULC exposure
        # ----------------------------------------------------

        lulc_exposure = []

        for class_value in sorted(
            LULC_RISK.keys()
        ):

            mask = (
                lulc_values_raw
                ==
                class_value
            )

            count = int(
                np.sum(mask)
            )

            if count == 0:

                continue

            percentage = (
                count
                /
                len(route)
                *
                100.0
            )

            lulc_exposure.append(
                {

                    "route_name":
                    route_name,

                    "lulc_class":
                    int(class_value),

                    "risk_value":
                    float(
                        LULC_RISK[
                            class_value
                        ]
                    ),

                    "cells":
                    count,

                    "percentage":
                    float(
                        percentage
                    )
                }
            )

        # ----------------------------------------------------
        # Slope exposure
        # ----------------------------------------------------

        slope_exposure = {

            "low_0_5_deg":
            int(slope_low),

            "moderate_5_15_deg":
            int(slope_moderate),

            "high_15_30_deg":
            int(slope_high),

            "very_high_gt_30_deg":
            int(slope_very_high)
        }

        # ----------------------------------------------------
        # Result
        # ----------------------------------------------------

        result = {

            "route_name":
            route_name,

            "status":
            "success",

            "route_cells":
            int(len(route)),

            "route_distance_m":
            float(route_distance_m),

            "route_distance_km":
            float(
                route_distance_m / 1000.0
            ),

            "mean_slope_deg":
            mean_slope,

            "max_slope_deg":
            max_slope,

            "terrain_risk":
            mean_terrain_risk,

            "lulc_risk":
            mean_lulc_risk,

            "combined_risk":
            combined_risk,

            "risk_category":
            risk_category,

            "high_risk_cells":
            high_risk_cells,

            "high_risk_percentage":
            float(
                high_risk_percentage
            ),

            "high_risk_distance_m":
            float(
                high_risk_distance_m
            ),

            "high_risk_distance_km":
            float(
                high_risk_distance_m
                /
                1000.0
            ),

            "high_risk_sections":
            int(
                high_risk_sections
            ),

            "slope_exposure":
            slope_exposure,

            "lulc_exposure":
            lulc_exposure,

            "high_risk_section_records":
            section_records
        }

        return result


    # ========================================================
    # ANALYZE FOUR ROUTES
    # ========================================================

    def analyze_routes(
        self,
        route_results
    ):

        # ----------------------------------------------------
        # Create surfaces once
        # ----------------------------------------------------

        self.create_risk_surfaces()

        results = {}

        for route_key, route_result in route_results.items():

            route_name = route_result.get(
                "route_name",
                route_key
            )

            route = route_result.get(
                "route"
            )

            print(
                "\n"
                + "-" * 70
            )

            print(
                f"RISK ANALYSIS: {route_name}"
            )

            print(
                "-" * 70
            )

            if route is None:

                print(
                    "Route unavailable."
                )

                results[
                    route_key
                ] = {

                    "route_name":
                    route_name,

                    "status":
                    "failed"
                }

                continue

            result = self.analyze_route(
                route,
                route_name
            )

            results[
                route_key
            ] = result

            print(
                "Mean slope:",
                round(
                    result[
                        "mean_slope_deg"
                    ],
                    3
                ),
                "degrees"
            )

            print(
                "Maximum slope:",
                round(
                    result[
                        "max_slope_deg"
                    ],
                    3
                ),
                "degrees"
            )

            print(
                "Terrain risk:",
                round(
                    result[
                        "terrain_risk"
                    ],
                    4
                )
            )

            print(
                "LULC risk:",
                round(
                    result[
                        "lulc_risk"
                    ],
                    4
                )
            )

            print(
                "Combined risk:",
                round(
                    result[
                        "combined_risk"
                    ],
                    4
                )
            )

            print(
                "Risk category:",
                result[
                    "risk_category"
                ]
            )

            print(
                "High-risk cells:",
                result[
                    "high_risk_cells"
                ]
            )

            print(
                "High-risk distance:",
                round(
                    result[
                        "high_risk_distance_km"
                    ],
                    3
                ),
                "km"
            )

            print(
                "High-risk sections:",
                result[
                    "high_risk_sections"
                ]
            )

        return results


# ============================================================
# JSON SAFE
# ============================================================

def make_json_safe(
    obj
):

    if isinstance(
        obj,
        np.integer
    ):

        return int(obj)

    if isinstance(
        obj,
        np.floating
    ):

        return float(obj)

    if isinstance(
        obj,
        np.ndarray
    ):

        return obj.tolist()

    if isinstance(
        obj,
        tuple
    ):

        return list(obj)

    if isinstance(
        obj,
        dict
    ):

        return {
            key:
            make_json_safe(value)
            for key, value in obj.items()
        }

    if isinstance(
        obj,
        list
    ):

        return [
            make_json_safe(value)
            for value in obj
        ]

    return obj


# ============================================================
# SAVE RESULT
# ============================================================

def save_result(
    result,
    output_path
):

    os.makedirs(
        os.path.dirname(
            output_path
        ),
        exist_ok=True
    )

    safe_result = make_json_safe(
        result
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            safe_result,
            f,
            indent=4
        )

    print(
        "\nRisk result saved:"
    )

    print(
        output_path
    )


# ============================================================
# SAVE CSV SUMMARY
# ============================================================

def save_summary_csv(
    risk_results,
    output_path
):

    rows = []

    for route_key, result in risk_results.items():

        if result.get(
            "status"
        ) != "success":

            continue

        rows.append(
            {

                "route_key":
                route_key,

                "route_name":
                result[
                    "route_name"
                ],

                "route_cells":
                result[
                    "route_cells"
                ],

                "route_distance_km":
                result[
                    "route_distance_km"
                ],

                "mean_slope_deg":
                result[
                    "mean_slope_deg"
                ],

                "max_slope_deg":
                result[
                    "max_slope_deg"
                ],

                "terrain_risk":
                result[
                    "terrain_risk"
                ],

                "lulc_risk":
                result[
                    "lulc_risk"
                ],

                "combined_risk":
                result[
                    "combined_risk"
                ],

                "risk_category":
                result[
                    "risk_category"
                ],

                "high_risk_cells":
                result[
                    "high_risk_cells"
                ],

                "high_risk_percentage":
                result[
                    "high_risk_percentage"
                ],

                "high_risk_distance_km":
                result[
                    "high_risk_distance_km"
                ],

                "high_risk_sections":
                result[
                    "high_risk_sections"
                ]
            }
        )

    df = pd.DataFrame(
        rows
    )

    df.to_csv(
        output_path,
        index=False
    )

    print(
        "\nRisk summary CSV saved:"
    )

    print(
        output_path
    )


# ============================================================
# TEST WITH ROUTING ENGINE V2
# ============================================================

if __name__ == "__main__":

    print(
        "\n"
        + "=" * 70
    )

    print(
        "DYNAMIC RISK ENGINE V1 TEST"
    )

    print(
        "=" * 70
    )

    # --------------------------------------------------------
    # Import routing engine
    # --------------------------------------------------------

    from routing_engine_v2 import (
        RoutingEngineV2
    )

    # --------------------------------------------------------
    # Test coordinates
    # --------------------------------------------------------

    START_LAT = 27.5619

    START_LON = 96.0374

    END_LAT = 27.383898

    END_LON = 95.333229

    # --------------------------------------------------------
    # Generate routes
    # --------------------------------------------------------

    routing_engine = RoutingEngineV2()

    routing_result = (
        routing_engine.run_route_analysis(
            start_lat=START_LAT,
            start_lon=START_LON,
            end_lat=END_LAT,
            end_lon=END_LON
        )
    )

    # --------------------------------------------------------
    # Initialize risk engine
    # --------------------------------------------------------

    risk_engine = DynamicRiskEngine()

    # --------------------------------------------------------
    # Analyze routes
    # --------------------------------------------------------

    risk_results = (
        risk_engine.analyze_routes(
            routing_result[
                "routes"
            ]
        )
    )

    # --------------------------------------------------------
    # Save JSON
    # --------------------------------------------------------

    json_output = os.path.join(
        OUTPUT_DIR,
        "risk_engine_dynamic_v1_test.json"
    )

    save_result(
        risk_results,
        json_output
    )

    # --------------------------------------------------------
    # Save CSV
    # --------------------------------------------------------

    csv_output = os.path.join(
        OUTPUT_DIR,
        "risk_engine_dynamic_v1_summary.csv"
    )

    save_summary_csv(
        risk_results,
        csv_output
    )

    # --------------------------------------------------------
    # Final summary
    # --------------------------------------------------------

    print(
        "\n"
        + "=" * 70
    )

    print(
        "DYNAMIC RISK ENGINE V1 COMPLETE"
    )

    print(
        "=" * 70
    )

    for route_key, result in risk_results.items():

        if result.get(
            "status"
        ) != "success":

            continue

        print(
            f"\n{result['route_name']}"
        )

        print(
            "  Risk:",
            round(
                result[
                    "combined_risk"
                ],
                4
            )
        )

        print(
            "  Category:",
            result[
                "risk_category"
            ]
        )

        print(
            "  High-risk distance:",
            round(
                result[
                    "high_risk_distance_km"
                ],
                3
            ),
            "km"
        )

    print(
        "\n"
        + "=" * 70
    )